name: Deploy Site to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docu/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: docu/package-lock.json

      - name: Install Docusaurus dependencies
        run: |
          cd docu
          npm install

      - name: Build Docusaurus
        run: |
          cd docu
          npm run build

      - name: Create combined site structure
        run: |
          echo "--- Listing contents of docu/build before copying ---"
          ls -R docu/build
          
          # Create the main site directory
          mkdir -p _site
          
          # Copy the main docs (mini marketplace) to root
          cp -r docs/* _site/
          
          # Copy Docusaurus build to /docu subdirectory
          # Since Docusaurus baseUrl is already /docu/, we copy to root and let it handle the paths
          cp -r docu/build/* _site/

          echo "--- Listing contents of _site after copying ---"
          ls -R _site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4