name: Deploy Website and Docusaurus

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'docu/package-lock.json'

      - name: Install and Build Docusaurus
        run: |
          cd docu
          npm install
          npm run build

      - name: Prepare deployment directory
        run: |
          mkdir -p _site/docu
          # Copy main site content
          cp -a docs/. _site/
          # Copy docusaurus build content (including dotfiles)
          cp -a docu/build/. _site/docu/
          # Ensure .nojekyll file exists at the root
          touch _site/.nojekyll
          echo "--- Contents of deployment directory ---"
          ls -laR _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: aitmpl.com
