# DEPRECATED: This workflow has been replaced by simple-tracking.yml
# This file is kept for reference only and should not be used
# The new workflow uses manual workflow_dispatch instead of repository_dispatch

name: Handle Download Tracking (DEPRECATED)

on:
  # Disabled all triggers - workflow is deprecated
  # repository_dispatch:
  #   types: [component_download]
  workflow_dispatch:
    inputs:
      deprecated_notice:
        description: 'This workflow is DEPRECATED. Use simple-tracking.yml instead'
        required: true
        default: 'DEPRECATED'

permissions:
  contents: read
  issues: write

jobs:
  track-download:
    runs-on: ubuntu-latest
    if: github.repository == 'davila7/claude-code-templates'
    
    steps:
      - name: Create tracking issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract data from client payload
          COMPONENT_TYPE="${{ github.event.client_payload.component_type }}"
          COMPONENT_NAME="${{ github.event.client_payload.component_name }}"
          TIMESTAMP="${{ github.event.client_payload.timestamp }}"
          SESSION_ID="${{ github.event.client_payload.session_id }}"
          PLATFORM="${{ github.event.client_payload.environment.platform }}"
          ARCH="${{ github.event.client_payload.environment.arch }}"
          NODE_VERSION="${{ github.event.client_payload.environment.node_version }}"
          CLI_VERSION="${{ github.event.client_payload.environment.cli_version }}"
          
          # Create issue title
          DATE=$(echo "$TIMESTAMP" | cut -d'T' -f1)
          TITLE="📊 ${COMPONENT_TYPE}:${COMPONENT_NAME} - ${DATE}"
          
          # Create JSON payload for issue body
          JSON_PAYLOAD=$(cat <<EOF
          {
            "event": "component_download",
            "component_type": "$COMPONENT_TYPE",
            "component_name": "$COMPONENT_NAME",
            "timestamp": "$TIMESTAMP",
            "session_id": "$SESSION_ID",
            "environment": {
              "node_version": "$NODE_VERSION",
              "platform": "$PLATFORM",
              "arch": "$ARCH",
              "cli_version": "$CLI_VERSION"
            },
            "metadata": ${{ toJson(github.event.client_payload.metadata) }}
          }
          EOF
          )
          
          # Create issue body
          BODY=$(cat <<EOF
          \`\`\`json
          $JSON_PAYLOAD
          \`\`\`
          
          <!-- ANALYTICS_DATA -->
          Component: **${COMPONENT_NAME}** (${COMPONENT_TYPE})  
          Platform: ${PLATFORM} ${ARCH}  
          Node: ${NODE_VERSION}  
          CLI: ${CLI_VERSION}  
          Session: \`${SESSION_ID}\`
          EOF
          )
          
          # Create the issue using GitHub CLI
          gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --label "📊 analytics,download-tracking,type:$COMPONENT_TYPE" \
            --repo "${{ github.repository }}"
          
          echo "✅ Tracking issue created successfully"

      - name: Log tracking event
        run: |
          echo "📊 Tracked download:"
          echo "  Component: ${{ github.event.client_payload.component_name }}"
          echo "  Type: ${{ github.event.client_payload.component_type }}"
          echo "  Session: ${{ github.event.client_payload.session_id }}"
          echo "  Platform: ${{ github.event.client_payload.environment.platform }}"